CREATE DATABASE IF NOT EXISTS ticket_manager;
USE ticket_manager;

CREATE TABLE User (
    USER_ID        INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL       VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD       VARCHAR(255) NOT NULL,
    NAME           VARCHAR(100) NOT NULL,
    BIRTHDATE      DATETIME NOT NULL,
    MOBILE_NUMBER  VARCHAR(15) NOT NULL UNIQUE,
    GENDER         CHAR(1) NOT NULL,
    ROLE           ENUM('Manager','Requestor') NOT NULL DEFAULT 'Requestor'
);

CREATE TABLE Ticket (
    TICKET_ID     INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID       INT NOT NULL,
    DESCRIPTION   VARCHAR(255) NOT NULL,
    REQUEST_TYPE  VARCHAR(100) NOT NULL,
    STATUS        VARCHAR(100) NOT NULL,
    CREATED_AT    DATETIME NOT NULL,
    LAST_UPDATED  DATETIME NOT NULL,
    KEY fk_ticket_user (USER_ID),
    CONSTRAINT fk_ticket_user
        FOREIGN KEY (USER_ID)
        REFERENCES User (USER_ID)
        ON DELETE CASCADE
)